Avnu paymaster
Endur-fi/client pull request #91
Opened 2024-12-31 14:21 UTC by Benjtalkshow

Closes #64 
# Add Avnu Paymaster Integration

## Overview
Integrates Avnu Paymaster to enable gas fee payments using ERC20 tokens (ETH, STRK, USDT, USDC, DAI) instead of only ETH.

## Changes
- Added `TokenSelector` component for token selection UI
- Added `useAvnuPaymaster` hook for paymaster integration
- Updated `stake.tsx` to support token-based gas payments
- Added real-time gas estimation in selected token
- Implemented fallback to regular transactions

## This is a work in progress

2025-01-05 01:46 UTC, Benjtalkshow commented
@akiraonstarknet 
Can you review. Thanks

2025-01-05 01:47 UTC, Benjtalkshow commented
Closes #64

2025-01-14 08:46 UTC, hemantwasthere requested changes
### Bugs:

1.  selected token for gas fee is not highlighted correctly, like selected token for gas fee is `STRK` but shows `ETH` on the dialog button.
2. `paymaster service unavailable` toast re-renders multiple times.
3. `XSTRK` isn't balance not reflecting in dialog.
4. use `prettier` for proper code formatting as per the configuration.

### UI Updates:
1. show a dropdown to show tokens for gas fees instead of dialog, use `shadcn's` dropdown component.
2. use the font `(FigTree)` for the consistency in dropdown as we're using this font almost everywhere.
3. beautify the toast as per the theme.
5. add some more white spacing.

2025-01-14 08:50 UTC, hemantwasthere commented on src/constants/index.ts
> +  { symbol: 'ETH', address: '0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7', logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png', decimals: 18 },
use the logo's from here

[strkfarm/starkfarm-client@c8b2b74/src/constants.ts#L6](https://github.com/strkfarm/starkfarm-client/blob/c8b2b745e8b15ec94102218df2145cb4002a467a/src/constants.ts#L6)
xSTRK logo: http://endur.fi/logo.svg

2025-01-14 08:52 UTC, hemantwasthere commented on src/hooks/use-avnu-paymaster.ts
> +const AVNU_BASE_URL = process.env.NEXT_PUBLIC_AVNU_API_URL || 'https://sepolia.api.avnu.fi';
add constants in `contants/index.ts` file

2025-01-14 10:37 UTC, Benjtalkshow commented
Ok, will make the requested changes

2025-01-21 09:50 UTC, akiraonstarknet commented
@Benjtalkshow any update?

2025-02-13 11:03 UTC, web3Gurung commented
@Benjtalkshow can we speed this up on priority?

2025-02-13 12:56 UTC, Benjtalkshow commented
> @Benjtalkshow can we speed this up on priority?
> 
> 

@web3Gurung and @akiraonstarknet 
I will make the changes as requested soon. I have not been available but I am active now.

2025-02-14 08:10 UTC, web3Gurung commented
@Benjtalkshow by when can we expect the pr from your end?

2025-02-14 10:54 UTC, Benjtalkshow commented
@web3Gurung 
Before Sunday

2025-02-14 12:39 UTC, web3Gurung commented
sounds good 🫡

On Fri, 14 Feb 2025 at 16:24, Nnaji Benjamin ***@***.***>
wrote:

> @web3Gurung <https://github.com/web3Gurung>
> Before Sunday
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Endur-fi/client/pull/91#issuecomment-2658977287>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARFSCGVMYLVGABQ2ZLHD2LL2PXDOZAVCNFSM6AAAAABUNRLGDKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNJYHE3TOMRYG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
> [image: Benjtalkshow]*Benjtalkshow* left a comment (Endur-fi/client#91)
> <https://github.com/Endur-fi/client/pull/91#issuecomment-2658977287>
>
> @web3Gurung <https://github.com/web3Gurung>
> Before Sunday
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Endur-fi/client/pull/91#issuecomment-2658977287>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARFSCGVMYLVGABQ2ZLHD2LL2PXDOZAVCNFSM6AAAAABUNRLGDKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNJYHE3TOMRYG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-02-16 19:32 UTC, Benjtalkshow commented
@web3Gurung 
I made soke changes, but i still have some additional fixes to implement

2025-02-16 19:43 UTC, Benjtalkshow commented
Will one last changes

2025-02-17 15:22 UTC, web3Gurung commented
@Benjtalkshow let us know when you're done with the pr from your side!

2025-02-17 21:43 UTC, Benjtalkshow commented
> @Benjtalkshow let us know when you're done with the pr from your side!

Alright sir

2025-03-09 11:32 UTC, merged